// Automaticlly generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for type:  SceMiSharedMemory::Tag

#pragma once

#include "bxactors/xat_scemi.h"


/// An alias or typedef name for BitT<7> to Tag
typedef BitT<7> Tag ;

