// Automaticlly generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for type:  Dut::TLMAddress

#pragma once

#include "bxactors/xat_scemi.h"


/// An alias or typedef name for BitT<32> to TLMAddress
typedef BitT<32> TLMAddress ;

