// Automaticlly generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for type:  TLM3Defines::TLMBurstLong

#pragma once

#include "bxactors/xat_scemi.h"


/// An alias or typedef name for BitT<15> to TLMBurstLong
typedef BitT<15> TLMBurstLong ;

