// Automaticlly generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for type:  TLM3Defines::TLMQos

#pragma once

#include "bxactors/xat_scemi.h"


/// An alias or typedef name for BitT<4> to TLMQos
typedef BitT<4> TLMQos ;

