// Automaticlly generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for type:  TLM3Defines::TLMRegion

#pragma once

#include "bxactors/xat_scemi.h"


/// An alias or typedef name for BitT<4> to TLMRegion
typedef BitT<4> TLMRegion ;

