// Automaticlly generated by: ::SceMiMsg
// DO NOT EDIT
// C++ Class with SceMi Message passing for type:  XilinxPCIE::TLPRegNum

#pragma once

#include "bxactors/xat_scemi.h"


/// An alias or typedef name for BitT<10> to TLPRegNum
typedef BitT<10> TLPRegNum ;

