#! /bin/sh
#
#
#       UMR Bus 3.0 USB Kernel Mode Device Driver for Linux
#
#              Copyright (C) 2013 - 2014 Synopsys, Inc.
#
#  This software is licensed under the terms of the GNU General Public License, version 2 (GPLv2),
#  as published by the Free Software Foundation, and you may redistribute and/or modify this
#  software under the terms of that license.
#
#  To the maximum extent permitted by law, this program is provided on an "AS IS" BASIS, WITHOUT 
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied, including, without limitation, 
#  any warranties or conditions of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A 
#  PARTICULAR PURPOSE. You are solely responsible for determining the appropriateness of using or 
#  redistributing the software and assume any risks  associated with your exercise of permissions under the GPLv2.
#  See the GPLv2 for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#
#
# chkconfig: 235 20 20
# description: Load/unload UMR Bus 3.0 USB device driver \
#              for Synopsys HAPS systems
#

### BEGIN INIT INFO
# Provides:            umr3usb
# Required-Start:      $local_fs $remote_fs $syslog
# Required-Stop:
# Default-Start:       2 3 5
# Default-Stop:        0 1 6
# Description:         UMR Bus 3.0 USB device driver (umr3usb) for Synopsys HAPS systems
### END INIT INFO


module="umr3usb"
device="umr3usb"
mode="666"

# Allow unsupported modules in SLES11, if disallowed by current configuration            
modprobe=/sbin/modprobe
if ${modprobe} -c | grep -q '^allow_unsupported_modules  *0'; then
    modprobe="${modprobe} --allow-unsupported-modules"
fi

case "$1" in
    start)
	echo "Loading UMR Bus 3.0 USB module"
	shift # get rid of parameter 'start'
	${modprobe} $module $* || exit 1
	;;
    stop)
	echo "Unloading UMR Bus 3.0 module"
	/sbin/modprobe -r $module
	;;
    restart)
        $0 stop
        $0 start
        ;;	
    *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac
exit 0
